apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: contour
spec:
  interval: 1m
  chart:
    spec:
      chart: contour
      version: "9.1.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: contour
