apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: contour
      version: "10.1.3"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: {{organization}}-{{team}}
