apiVersion: v1
kind: ConfigMap
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
  labels:
    organization: {{organization}}
    team: {{team}}
    app: {{workload}}
    deployment: {{deployment}}
  {{#each labels as |kv|}}
    {{kv.key}}: "{{{kv.value}}}"
  {{/each}}
data:
{{#each config as |kv|}}
  {{kv.key}}: "{{{kv.value}}}"
{{/each}}
