apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
  labels:
    organization: {{organization}}
    team: {{team}}
    app: {{workload}}
    deployment: {{deployment}}
  {{#each labels as |kv|}}
    {{kv.key}}: {{kv.value}}
  {{/each}}
spec:
  tls:
  - hosts:
      - {{deployment}}.{{workload}}.{{domain}}
    secretName: {{tlsSecret}}
  rules:
  - host: {{deployment}}.{{workload}}.{{domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{workload}}-{{deployment}}
            port:
              number: {{port}}