apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
  labels:
    organization: {{organization}}
    team: {{team}}
    app: {{workload}}
    deployment: {{deployment}}
  {{#each labels as |kv|}}
    {{kv.key}}: {{kv.value}}
  {{/each}}
spec:
  virtualhost:
    fqdn: {{deployment}}.{{workload}}.{{domain}}
  routes:
  - conditions: 
    - prefix: /
    services:
    - name: {{workload}}-{{deployment}}
      port: {{port}}
