apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
spec:
  dependsOn: cncf-infra-stable
resources:
  - configMap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
