apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
resources:
  - configMap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
