apiVersion: v1
kind: Service
metadata:
  name: {{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
  labels:
    organization: {{organization}}
    team: {{team}}
    workload: {{workload}}
    deployment: {{deployment}}
  {{#each labels as |kv|}}
    {{kv.key}}: {{kv.value}}
  {{/each}}
spec:
  selector:
    app: {{workload}}
  ports:
    - protocol: TCP
      port: {{port}}
      targetPort: {{containerPort}}
