apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
spec:
  interval: 1m
  chart:
    spec:
      chart: grafana
      version: "6.42.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
