apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
spec:
  url: https://grafana.github.io/helm-charts
  interval: 10m
