apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.38.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
  values:
    mode: deployment
    config: 
      exporters:
        otlp/honeycomb:
          endpoint: api.honeycomb.io:443
          headers:
            "x-honeycomb-team": "{{{honeycomb-api-key}}}"
      service:
        pipelines:
          traces:
            receivers: 
              - otlp
            exporters: 
              - otlp/honeycomb
