apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.43.2"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: {{organization}}-{{team}}
    mode: deployment
    config:
      exporters:
        receivers:
          otlp:
            protocols:
              grpc:
        logging:
          loglevel: info
        jaeger:
          endpoint: jaeger.{{organization}}-{{team}}.svc:14250
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: []
            exporters: [jaeger, logging]

