apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-{{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.43.2"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: {{organization}}-{{team}}
  values:
    mode: deployment
    config:
      receivers:
        otlp:
          protocols:
            grpc:
      exporters:
        logging:
          loglevel: info
        jaeger:
          endpoint: jaeger.{{organization}}-{{team}}.svc:14250
          tls:
            insecure: true
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: []
            exporters: [jaeger, logging]

