apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector-{{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.43.2"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: {{organization}}-{{team}}
  values:
    mode: deployment
    config:
      exporters:
        otlp:
          endpoint: ingest.lightstep.com:443
          headers:
            "lightstep-access-token": "{{lightstep-access-token}}"
      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: []
            exporters: [otlp]

