apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator-{{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger-operator
      version: "2.38.0"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: {{organization}}-{{team}}
  values:
    certs:
      certificate:
        namespace: {{organization}}-{{team}}

