apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
spec:
  interval: 1m
  chart:
    spec:
      chart: prometheus
      version: "15.16.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: {{organization}}-{{team}}-{{workload}}-{{deployment}}
