apiVersion: v1
kind: Secret
metadata:
  name: azure-log-analytics
  namespace: {{organization}}-{{team}}
type: Opaque
stringData:
  # TODO: Migrate to secrets store
  workspace_id: "{{{log-analytics-workspace-id}}}"
  key: "{{{log-analytics-key}}}"
