apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-{{workload}}-{{deployment}}
  namespace: {{organization}}-{{team}}
spec:
  interval: 1m
  chart:
    spec:
      chart: jaeger
      version: "0.65.4"
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: {{organization}}-{{team}}
  values:
    allInOne:
      enabled: true
