apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: {{organization}}-{{team}}
spec:
  url: https://jaegertracing.github.io/helm-charts
  interval: 10m
